### PR TITLE
Move to using FFT from stream executor to prevent issues

### LINKED ISSUE #24: Ramdom failing to associate CUDA stream issues?
I get the following issues sometimes (again, they are quite random, and hence quite hard to debug)

Failed to associate cuFFT plan with CUDA stream: 1

Mostly arising from: 

https://github.com/mrphys/tensorflow-nufft/blob/021090141fa7a6165b6cba5824c70659f506b644/tensorflow_nufft/cc/kernels/nufft_plan.cu.cc#L1887-L1890

Seems like cufft returns `cufftInvalidPlan` which is error code 1. I am a bit clueless on how to start on this one. I might as usual try to get a repro soon though. @jmontalt any idea if you faced this and any pointers where to start?

### PR DESCRIPTION
**Pull request by chaithyagr**
This should ideally resolve #24 

@jmontalt I will recompile after merge and test things on my end.
Can you please handle the review and any update to the code needed? I will be on vacation from tomorrow and I seem to have fixed it finally.

### CODE REVIEW

**Comment by chaithyagr** [comment]
Ahh I seem to have build issues post merge, lemme see quickly. Converting to draft.

**Comment by chaithyagr** [comment]
I guess ideally, as mentioned in #23 we really can remove cuFFT requirements. Tensorflow can handle it.

**Comment by jmontalt** [comment]
Amazing. Thank you very much! I will aim to review this and merge in the next few days!

**Comment by chaithyagr** [comment]
Well, I will need to get back to test it.
But based on first look, things seem good. I am a bit worried on how much duplication of code we are doing from tensorflow core, particularly for scratch allocator. I wonder if these helper functions are available in some include files

**Comment by chaithyagr** [comment]
Thank you for all the updates though, but I'll need some time to be back and test them.

**Comment by jmontalt** [comment]
No worries, have a look in your own time.

Unfortunately, the `CufftScratchAllocator` is not exposed in any header files. In addition, it has internal linkage (class is defined in an anonymous namespace), so I think we have no choice but to duplicate the implementation.

**Comment by chaithyagr** [comment]
Back from vacation, reviewing this soon..

**Comment by chaithyagr** [comment]
@jmontalt can we for now stay with tensorflow 2.8? Or we also need an upgrade of `tensorflow-mri`. 

On this note, I was also wondering if we can have different releases for all tensorflow versions with different pip packages? 
(Something like this is done by cupy through cupy-cuda110, cupy-cuda112 etc... ) This will prevent downstream projects having to constantly change the tensorflow.

**Comment by chaithyagr** [comment]
I think your updates to the codes are perfect @jmontalt , maybe we can proceed with merge. Thank you for your support

**Comment by jmontalt** [comment]
Great! Thank you for your contribution!

**Pull request merged**
